In [54]:
!pip install fsspec polars paramiko

Requirement already satisfied: fsspec in ./venv/lib/python3.12/site-packages (2026.2.0)
Requirement already satisfied: polars in ./venv/lib/python3.12/site-packages (1.39.3)
Requirement already satisfied: paramiko in ./venv/lib/python3.12/site-packages (4.0.0)
Requirement already satisfied: polars-runtime-32==1.39.3 in ./venv/lib/python3.12/site-packages (from polars) (1.39.3)
Requirement already satisfied: bcrypt>=3.2 in ./venv/lib/python3.12/site-packages (from paramiko) (5.0.0)
Requirement already satisfied: cryptography>=3.3 in ./venv/lib/python3.12/site-packages (from paramiko) (46.0.5)
Requirement already satisfied: invoke>=2.0 in ./venv/lib/python3.12/site-packages (from paramiko) (2.2.1)
Requirement already satisfied: pynacl>=1.5 in ./venv/lib/python3.12/site-packages (from paramiko) (1.6.2)
Requirement already satisfied: cffi>=2.0.0 in ./venv/lib/python3.12/site-packages (from cryptography>=3.3->paramiko) (2.0.0)
Requirement already satisfied: pycparser in ./venv/lib/python3.12/site-packages (from cffi>=2.0.0->cryptography>=3.3->paramiko) (3.0)

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [55]:
import polars as pl
import fsspec
import io

In [56]:
fs = fsspec.filesystem("sftp", 
                       host="localhost", 
                       port=2222, 
                       username="teste", 
                       password="123456")

In [57]:
with fs.open("/upload/microdados_enem_2024/DADOS/RESULTADOS_2024.csv", "rb") as f:
    content = f.read()

text = content.decode("latin-1")

SSHException: Server connection dropped:

In [ ]:
df_resultado = pl.read_csv(io.StringIO(text), separator=";")

In [ ]:
df_resultado.describe()

shape: (9, 6)
┌────────────┬───────────────┬───────────┬────────────────────┬───────────────────────┬────────────┐
│ statistic  ┆ NU_SEQUENCIAL ┆ SG_UF_ESC ┆ NO_MUNICIPIO_PROVA ┆ TX_RESPOSTAS_CN       ┆ NU_NOTA_CN │
│ ---        ┆ ---           ┆ ---       ┆ ---                ┆ ---                   ┆ ---        │
│ str        ┆ f64           ┆ str       ┆ str                ┆ str                   ┆ f64        │
╞════════════╪═══════════════╪═══════════╪════════════════════╪═══════════════════════╪════════════╡
│ count      ┆ 4.332944e6    ┆ 1565797   ┆ 4332944            ┆ 3004981               ┆ 3.004981e6 │
│ null_count ┆ 0.0           ┆ 2767147   ┆ 0                  ┆ 1327963               ┆ 1.327963e6 │
│ mean       ┆ 2166472.5     ┆ null      ┆ null               ┆ null                  ┆ 493.926412 │
│ std        ┆ 1.2508e6      ┆ null      ┆ null               ┆ null                  ┆ 79.061784  │
│ min        ┆ 1.0           ┆ AC        ┆ Abaetetuba         ┆ ********************* ┆ 0.0        │
│            ┆               ┆           ┆                    ┆ *********…            ┆            │
│ 25%        ┆ 1.083237e6    ┆ null      ┆ null               ┆ null                  ┆ 431.4      │
│ 50%        ┆ 2.166473e6    ┆ null      ┆ null               ┆ null                  ┆ 488.4      │
│ 75%        ┆ 3.249708e6    ┆ null      ┆ null               ┆ null                  ┆ 550.2      │
│ max        ┆ 4.332944e6    ┆ TO        ┆ Óbidos             ┆ EEEEEEEEEEEEEEEEEEEEE ┆ 867.2      │
│            ┆               ┆           ┆                    ┆ EEEEEEEEE…            ┆            │
└────────────┴───────────────┴───────────┴────────────────────┴───────────────────────┴────────────┘

In [ ]:
df_resultado.glimpse()

Rows: 4332944
Columns: 5
$ NU_SEQUENCIAL      <i64> 206403, 3604651, 1461268, 4301058, 3148322, 1035588, 3587454, 140768, 3541867, 3371353
$ SG_UF_ESC          <str> 'CE', 'SC', null, null, 'MA', null, 'PA', null, null, null
$ NO_MUNICIPIO_PROVA <str> 'Aratuba', 'Tijucas', 'Rolândia', 'Osasco', 'São Mateus do Maranhão', 'Natal', 'Belém', 'Natal', 'Sabará', 'Indaiatuba'
$ TX_RESPOSTAS_CN    <str> 'CAABADDBBBACACACDEABDBABDDCCBACDCCBAACCABCBAC', 'EBDEEADAECCAAEDBBEDABACDBCEEDDDEDBDDABDBCCECA', 'CABAECDBADDCDEACABEACEABEDDCEDCDCCBDBDBDDBDCC', 'DDAAECECCBDBECBCBEAAADCBDDBBBEDADBDCCEEBCDAAD', null, null, 'ECCDAACEAACCBAABCBBDBAECBDBCACBEEDBDDADEADDAC', 'BECBCDCEECCDDEDDAAACCEDBEEEBABBEEBEDEEEDDDDDC', null, 'EAEEADBCAABDCEBAEDACBDECCDBDBCEEBADCEEDEADDDD'
$ NU_NOTA_CN         <f64> 436.8, 521.9, 363.0, 550.7, null, null, 486.7, 482.7, null, 599.5

In [ ]:
with fs.open("/upload/microdados_enem_2024/DADOS/ITENS_PROVA_2024.csv", "rb") as f:
    content = f.read()

text = content.decode("latin-1")

df_itens_prova = pl.read_csv(io.StringIO(text), separator=";")

In [ ]:
df_itens_prova

shape: (5_550, 14)
┌────────────┬─────────┬─────────┬─────────────┬───┬─────────┬──────────┬───────────┬──────────────┐
│ CO_POSICAO ┆ SG_AREA ┆ CO_ITEM ┆ TX_GABARITO ┆ … ┆ TX_COR  ┆ CO_PROVA ┆ TP_LINGUA ┆ IN_ITEM_ADAP │
│ ---        ┆ ---     ┆ ---     ┆ ---         ┆   ┆ ---     ┆ ---      ┆ ---       ┆ TADO         │
│ i64        ┆ str     ┆ i64     ┆ str         ┆   ┆ str     ┆ i64      ┆ str       ┆ ---          │
│            ┆         ┆         ┆             ┆   ┆         ┆          ┆           ┆ i64          │
╞════════════╪═════════╪═════════╪═════════════╪═══╪═════════╪══════════╪═══════════╪══════════════╡
│ 6          ┆ LC      ┆ 150678  ┆ E           ┆ … ┆ AZUL    ┆ 1395     ┆ null      ┆ 0            │
│ 7          ┆ LC      ┆ 14475   ┆ D           ┆ … ┆ AZUL    ┆ 1353     ┆ null      ┆ 0            │
│ 7          ┆ LC      ┆ 14475   ┆ D           ┆ … ┆ AZUL    ┆ 1441     ┆ null      ┆ 0            │
│ 7          ┆ LC      ┆ 16575   ┆ A           ┆ … ┆ AMARELA ┆ 1354     ┆ null      ┆ 0            │
│ 7          ┆ LC      ┆ 16575   ┆ A           ┆ … ┆ AMARELA ┆ 1442     ┆ null      ┆ 0            │
│ …          ┆ …       ┆ …       ┆ …           ┆ … ┆ …       ┆ …        ┆ …         ┆ …            │
│ 176        ┆ MT      ┆ 17549   ┆ E           ┆ … ┆ CINZA   ┆ 1326     ┆ null      ┆ 0            │
│ 176        ┆ MT      ┆ 17549   ┆ E           ┆ … ┆ CINZA   ┆ 1366     ┆ null      ┆ 0            │
│ 176        ┆ MT      ┆ 27923   ┆ A           ┆ … ┆ AMARELA ┆ 1324     ┆ null      ┆ 0            │
│ 176        ┆ MT      ┆ 27923   ┆ A           ┆ … ┆ AMARELA ┆ 1364     ┆ null      ┆ 0            │
│ 176        ┆ MT      ┆ 76177   ┆ D           ┆ … ┆ AMARELA ┆ 1408     ┆ null      ┆ 0            │
└────────────┴─────────┴─────────┴─────────────┴───┴─────────┴──────────┴───────────┴──────────────┘

shape: (0, 6)
┌───────────────┬───────────┬────────────────────┬─────────────────┬────────────┬─────────┐
│ NU_SEQUENCIAL ┆ SG_UF_ESC ┆ NO_MUNICIPIO_PROVA ┆ TX_RESPOSTAS_CN ┆ NU_NOTA_CN ┆ TP_SEXO │
│ ---           ┆ ---       ┆ ---                ┆ ---             ┆ ---        ┆ ---     │
│ i64           ┆ str       ┆ str                ┆ str             ┆ f64        ┆ str     │
╞═══════════════╪═══════════╪════════════════════╪═════════════════╪════════════╪═════════╡
└───────────────┴───────────┴────────────────────┴─────────────────┴────────────┴─────────┘

In [ ]:
df_resultado.columns

['NU_SEQUENCIAL',
 'SG_UF_ESC',
 'NO_MUNICIPIO_PROVA',
 'TX_RESPOSTAS_CN',
 'NU_NOTA_CN']

In [ ]:
df_participantes

shape: (4_332_944, 38)
┌──────────────┬────────┬─────────────────┬─────────┬───┬──────┬──────┬──────┬──────┐
│ NU_INSCRICAO ┆ NU_ANO ┆ TP_FAIXA_ETARIA ┆ TP_SEXO ┆ … ┆ Q020 ┆ Q021 ┆ Q022 ┆ Q023 │
│ ---          ┆ ---    ┆ ---             ┆ ---     ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
│ i64          ┆ i64    ┆ i64             ┆ str     ┆   ┆ str  ┆ str  ┆ str  ┆ str  │
╞══════════════╪════════╪═════════════════╪═════════╪═══╪══════╪══════╪══════╪══════╡
│ 210062064233 ┆ 2024   ┆ 5               ┆ F       ┆ … ┆ B    ┆ B    ┆ E    ┆ A    │
│ 210062064234 ┆ 2024   ┆ 11              ┆ F       ┆ … ┆ B    ┆ A    ┆ C    ┆ A    │
│ 210062064235 ┆ 2024   ┆ 11              ┆ F       ┆ … ┆ B    ┆ A    ┆ D    ┆ A    │
│ 210062064236 ┆ 2024   ┆ 3               ┆ F       ┆ … ┆ B    ┆ A    ┆ D    ┆ A    │
│ 210062064237 ┆ 2024   ┆ 16              ┆ M       ┆ … ┆ B    ┆ A    ┆ B    ┆ A    │
│ …            ┆ …      ┆ …               ┆ …       ┆ … ┆ …    ┆ …    ┆ …    ┆ …    │
│ 210066495575 ┆ 2024   ┆ 7               ┆ M       ┆ … ┆ B    ┆ A    ┆ C    ┆ A    │
│ 210066495576 ┆ 2024   ┆ 6               ┆ M       ┆ … ┆ B    ┆ A    ┆ C    ┆ A    │
│ 210066495577 ┆ 2024   ┆ 4               ┆ F       ┆ … ┆ B    ┆ B    ┆ B    ┆ A    │
│ 210066495578 ┆ 2024   ┆ 2               ┆ F       ┆ … ┆ A    ┆ A    ┆ B    ┆ A    │
│ 210066495579 ┆ 2024   ┆ 1               ┆ F       ┆ … ┆ B    ┆ A    ┆ D    ┆ D    │
└──────────────┴────────┴─────────────────┴─────────┴───┴──────┴──────┴──────┴──────┘